app = "gatch-it-all"
primary_region = "ams"

[env]
NODE_ENV = "production"

[http_service]
force_https = true
internal_port = 3000

[[services]]
internal_port = 3000
protocol = "tcp"

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443