# fly.toml app configuration file generated for gatch-it-all on 2026-09-10T13:15:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gatch-it-all"
primary_region = 'ams'

[env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=768"

[http_service]
force_https = true
internal_port = 3000
min_machines_running = 1
auto_start_machines = true
auto_stop_machines = true

[build]

  [build.args]
    VITE_CLERK_PUBLISHABLE_KEY = "pk_live_Y2xlcmsuZ2F0Y2hpdGFsbC5jb20k"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '768mb'
  memory_mb = 768
  processes = ['app']
  size = 'shared-cpu-1x'
